[build]
  command = "npm run build"
  publish = "build/"
  base ="my-app/"

[[redirects]]
    to="/.netlify/functions/api:splat"
    from="/*"
    status=200 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200