import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/81/18/81183e2aa7725b4bac2c5d7e9e8072ecbdd0eee1.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    category: 'Women',
    size: ['s', 'm', 'l', 'xl'],
    title: 'High Waist Sports tights',
    price: '1199',
    rating: '3.9',
    trending: false,
    delivery_time: '9',
    reviews: '2.9k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/2c/9c/2c9cfce593e55b63d02404a57f8ebcfb62e46604.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    category: 'Women',
    size: ['s', 'm', 'xl'],
    title: 'Cut-out-detail sports tights',
    price: '1499',
    rating: '3.2',
    trending: false,
    delivery_time: '8',
    reviews: '2.2k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/67/50/6750460774e889ec6d93a681f82fb70faf86016d.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'm', 'l'],
    category: 'Women',
    title: 'High Waist Shaping tights',
    price: '1199',
    rating: '3.1',
    trending: true,
    delivery_time: '3',
    reviews: '2.6k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/ef/d6/efd6ab9f12af41848ca2dcaf465d3672bf714a76.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'm', 'l', 'xl'],
    category: 'Women',
    title: 'Cut-out-detail sports tights',
    price: '899',
    rating: '1.9',
    trending: true,
    delivery_time: '5',
    reviews: '2.7k',
    in_stock: false,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/4d/08/4d08b2704b51a27cba11e64d27b54c1d0d92ecf1.jpg],origin[dam],category[ladies_lingerie_bras_bralettes],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'm', 'l', 'xl'],
    category: 'Women',
    title: "Light Support Sports bralette",
    price: '999',
    rating: '4.5',
    trending: false,
    delivery_time: '7',
    reviews: '2.8k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/35/29/352933e04cdbd226ff56e50cd79a2d915ca66a97.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['m', 'l', 'xl'],
    category: 'Women',
    title: "Sports popover jacket",
    price: '1499',
    rating: '1.8',
    trending: true,
    delivery_time: '7',
    reviews: '2.9k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/e2/83/e28306e7f82abcb31434379da7698d479d13ab2b.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['m', 'l', 'xl'],
    category: 'Women',
    title: 'Seamless sports tight',
    price: '399',
    rating: '2.8',
    trending: true,
    delivery_time: '8',
    reviews: '4.9k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/26/10/2610647bd33a73b282531dbda3fda931591e3c2a.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['m', 'l', 'xl'],
    category: 'Women',
    title: "Lightweight running shorts",
    price: '499',
    rating: '2.8',
    trending: true,
    delivery_time: '3',
    reviews: '4.3k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/1a/19/1a196ab8c98cfc53e48f75f752e55746304eba9c.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'm', 'l', 'xl'],
    category: 'Women',
    title: "LSports wrap skirt",
    price: '1299',
    rating: '4.8',
    trending: true,
    delivery_time: '5',
    reviews: '3.3k',
    in_stock: false,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/9f/e7/9fe76d26c561554d4678f126eefd47a4d5e738cb.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'l', 'xl'],
    category: 'Women',
    title: "Cropped sports top",
    price: '1199',
    rating: '3.8',
    trending: true,
    delivery_time: '7',
    reviews: '3.4k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/27/16/27168c044485b19b54519014202acf100e55d196.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'm', 'l', 'xl'],
    category: 'Women',
    title: "Wide High Jeans",
    price: '1599',
    rating: '4.8',
    trending: true,
    delivery_time: '2',
    reviews: '4.4k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/79/4a/794afddb032b13021106ec59bb7000e520e1f5a4.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'm', 'l'],
    category: 'Women',
    title: "Wide twill trousers",
    price: '599',
    rating: '4.8',
    trending: true,
    delivery_time: '2',
    reviews: '4.4k',
    in_stock: true,
  },





  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/b2/5d/b25df154049847b8cc930f44aa5a0e9175cf4a81.jpg],origin[dam],category[],type[DESCRIPTIVESTILLLIFE],res[m],hmver[2]&call=url[file:/product/style]",
    category: 'men',
    size: ['s', 'm', 'l', 'xl'],
    title: "Cargo joggers",
    price: '1199',
    rating: '3.9',
    trending: false,
    delivery_time: '9',
    reviews: '2.9k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/f2/18/f2185ee80f5aa1be0a307ee0b2f74798a28f14ef.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    category: 'men',
    size: ['s', 'm', 'xl'],
    title: "Relaxed Fit Sweatshirt",
    price: '1499',
    rating: '3.2',
    trending: false,
    delivery_time: '8',
    reviews: '2.2k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/da/d8/dad83bb0763845cc86e8ff7e22bde233f12a7233.jpg],origin[dam],category[men_shoes_sandals_espandrillos],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'm', 'l'],
    category: 'men',
    title: "Leather mules",
    price: '1199',
    rating: '3.1',
    trending: true,
    delivery_time: '3',
    reviews: '2.6k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/a9/eb/a9ebb33395b09b39b122e1802f8e085cd5bf2ed2.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'm', 'l', 'xl'],
    category: 'men',
    title: "Regular Fit Joggers",
    price: '899',
    rating: '1.9',
    trending: true,
    delivery_time: '5',
    reviews: '2.7k',
    in_stock: false,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/8b/b7/8bb7056167edd6ad90ce5b584190fc1be2f7c837.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'm', 'l', 'xl'],
    category: 'men',
    title: "Backpack",
    price: '999',
    rating: '4.5',
    trending: false,
    delivery_time: '7',
    reviews: '2.8k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/cc/78/cc783b01c22bb9a1f73293e2ac74c6d4c2727298.jpg],origin[dam],category[],type[DESCRIPTIVESTILLLIFE],res[m],hmver[2]&call=url[file:/product/main]",
    size: ['m', 'l', 'xl'],
    category: 'men',
    title: "Relaxed Fit Sweatshirt",
    price: '1499',
    rating: '1.8',
    trending: true,
    delivery_time: '7',
    reviews: '2.9k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/16/df/16dfa90713a5a5feafbf865f3ec5ff32cf844841.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['m', 'l', 'xl'],
    category: 'men',
    title: "Regular Fit sweatshirt shorts",
    price: '399',
    rating: '2.8',
    trending: true,
    delivery_time: '8',
    reviews: '4.9k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/40/97/40977e516f8b91079318825df532cc1964566779.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['m', 'l', 'xl'],
    category: 'men',
    title: "Relaxed Fit Hoodie",
    price: '499',
    rating: '2.8',
    trending: true,
    delivery_time: '3',
    reviews: '4.3k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/57/ab/57ab9bbb793a799acfab98d6b4cb717f0cc27b18.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'm', 'l', 'xl'],
    category: 'men',
    title: "Relaxed Fit Linen-blend shirt",
    price: '1299',
    rating: '4.8',
    trending: true,
    delivery_time: '5',
    reviews: '3.3k',
    in_stock: false,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/49/56/49560dfa45732ed844e8e4742afdca248ee60f9f.jpg],origin[dam],category[men_tshirtstanks_shortsleeve],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'l', 'xl'],
    category: 'men',
    title: "Relaxed Fit T-shirt",
    price: '1199',
    rating: '3.8',
    trending: true,
    delivery_time: '7',
    reviews: '3.4k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/b7/6a/b76ac8c60dae22679b69f9f94f1bb94217bb820b.jpg],origin[dam],category[men_tshirtstanks_shortsleeve],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'm', 'l', 'xl'],
    category: 'men',
    title: "Regular Fit Round-neck T-shirt",
    price: '1599',
    rating: '4.8',
    trending: true,
    delivery_time: '2',
    reviews: '4.4k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/70/61/706176203406264a91657691aff63c1e65ba808d.jpg],origin[dam],category[men_shirts_shortsleeved],type[DESCRIPTIVESTILLLIFE],res[m],hmver[2]&call=url[file:/product/main]",
    size: ['s', 'm', 'l'],
    category: 'men',
    title: "Patterned resort shirt",
    price: '599',
    rating: '4.8',
    trending: true,
    delivery_time: '2',
    reviews: '4.4k',
    in_stock: true,
  },





  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/a8/d4/a8d4ea7fd0522cdd7dff9adf2df2ae79b7a77159.jpg],origin[dam],category[kids_baby_girl_clothing_tops_tshirts],type[DESCRIPTIVESTILLLIFE],res[m],hmver[2]&call=url[file:/product/main]",
    category: 'kids',
    size: ['s', 'm', 'l', 'xl'],
    title: "Printed T-shirt",
    price: '1199',
    rating: '3.9',
    trending: false,
    delivery_time: '9',
    reviews: '2.9k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/f9/8a/f98abcbbc3969be32c2acec915a873835c198813.jpg],origin[dam],category[kids_girls_accessories_hairaccessories],type[DESCRIPTIVESTILLLIFE],res[m],hmver[2]&call=url[file:/product/main]",
    category: 'kids',
    size: ['s', 'm', 'xl'],
    title:
      "10-pack hair clips",
    price: '1499',
    rating: '3.2',
    trending: false,
    delivery_time: '8',
    reviews: '2.2k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:

      "https://lp2.hm.com/hmgoepprod?set=source[/32/27/322739698071375d0000cb67494ebfa22de359a2.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'm', 'l'],
    category: 'kids',
    title: "2-piece top and shorts set",
    price: '1199',
    rating: '3.1',
    trending: true,
    delivery_time: '3',
    reviews: '2.6k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/76/44/76445217d4a50e14dde63bd3feb5fa8f913c9b9b.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'm', 'l', 'xl'],
    category: 'kids',
    title: "2-piece terry set",
    price: '899',
    rating: '1.9',
    trending: true,
    delivery_time: '5',
    reviews: '2.7k',
    in_stock: false,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/60/aa/60aa3430d85015784e00159df4f83655463caf8e.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'm', 'l', 'xl'],
    category: 'kids',
    title:
      "2-piece embroidery-detail set",
    price: '999',
    rating: '4.5',
    trending: false,
    delivery_time: '7',
    reviews: '2.8k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/c4/98/c49846bd8439995ddd18c88f6453026dfa1f6e11.jpg],origin[dam],category[kids_boys_clothing_nightwear_pyjamas],type[DESCRIPTIVESTILLLIFE],res[m],hmver[2]&call=url[file:/product/main]",
    size: ['m', 'l', 'xl'],
    category: 'kids',
    title: "Pyjama T-shirt and shorts",
    price: '1499',
    rating: '1.8',
    trending: true,
    delivery_time: '7',
    reviews: '2.9k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:

      "https://lp2.hm.com/hmgoepprod?set=source[/c9/e0/c9e064c94396c8f4e6754ecce6999e49229ca1ae.jpg],origin[dam],category[kids_baby_boy_setsoutfits],type[DESCRIPTIVESTILLLIFE],res[m],hmver[2]&call=url[file:/product/main]",
    size: ['m', 'l', 'xl'],
    category: 'kids',
    title:
      "6-piece jersey set",
    price: '399',
    rating: '2.8',
    trending: true,
    delivery_time: '8',
    reviews: '4.9k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/a5/10/a510cfd3f54a6ef6f08d7b9b4338e82d2567dc03.jpg],origin[dam],category[kids_baby_girl_clothing_bodysuits],type[DESCRIPTIVESTILLLIFE],res[m],hmver[2]&call=url[file:/product/main]",
    size: ['m', 'l', 'xl'],
    category: 'kids',
    title: "3-pack short-sleeved bodysuits",
    price: '499',
    rating: '2.8',
    trending: true,
    delivery_time: '3',
    reviews: '4.3k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/38/68/386883e16c11d2434906423422627db7ac344b3c.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'm', 'l', 'xl'],
    category: 'kids',
    title:
      "Cut-out dress",
    price: '1299',
    rating: '4.8',
    trending: true,
    delivery_time: '5',
    reviews: '3.3k',
    in_stock: false,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/19/a6/19a6c3a63ee1de66d7a61a31411c01c56b4b4484.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'l', 'xl'],
    category: 'kids',
    title: "2-piece printed set",
    price: '1199',
    rating: '3.8',
    trending: true,
    delivery_time: '7',
    reviews: '3.4k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/4d/59/4d59545f4ea37c45b5a59e22d9b82518dd1f2bb0.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[1]&call=url[file:/product/main]",
    size: ['s', 'm', 'l', 'xl'],
    category: 'kids',
    title: "5-pack jersey shorts",
    price: '1599',
    rating: '4.8',
    trending: true,
    delivery_time: '2',
    reviews: '4.4k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/ac/d3/acd350fccf73076117c52c3ccfa717a759ecc7c2.jpg],origin[dam],category[],type[LOOKBOOK],res[m],hmver[2]&call=url[file:/product/main]",
    size: ['s', 'm', 'l'],
    category: 'kids',
    title: "2-piece set",
    price: '599',
    rating: '4.8',
    trending: true,
    delivery_time: '2',
    reviews: '4.4k',
    in_stock: true,
  },



];
